spring.application.name=NotifyService

server.port=8085

spring.rabbitmq.host=127.0.0.1
spring.rabbitmq.port=5672
spring.rabbitmq.username=admin
spring.rabbitmq.password=admin
spring.rabbitmq.virtual-host=/
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=hoanhsang24@gmail.com
spring.mail.password=oidp tree cspv ebpk
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true